import { ModifierImpl } from "./ModifierImpl";
import type { BoxAlignment, HorizontalAlignment, VerticalAlignment } from "../../components/layouts/Alignment";
import type { Shape } from "../shapes/Shape";
import type { ColorToken } from "../theme/ColorScheme";
type PaddingValue = number | {
    top?: number;
    bottom?: number;
    start?: number;
    end?: number;
};
export declare const Modifier: {
    readonly empty: () => ModifierImpl;
    readonly padding: (valueOrParams?: PaddingValue, unit?: string) => ModifierImpl;
    readonly paddingHorizontal: (value: number) => ModifierImpl;
    readonly paddingVertical: (value: number) => ModifierImpl;
    readonly border: (width: number, color: string, shape?: Shape) => ModifierImpl;
    readonly clickable: (onClick: () => void) => ModifierImpl;
    readonly offset: (x: number, y: number) => ModifierImpl;
    readonly verticalScroll: (enabled?: boolean) => ModifierImpl;
    readonly horizontalScroll: (enabled?: boolean) => ModifierImpl;
    readonly align: (alignment: BoxAlignment | HorizontalAlignment | VerticalAlignment) => ModifierImpl;
    readonly fillMaxWidth: () => ModifierImpl;
    readonly fillMaxHeight: () => ModifierImpl;
    readonly fillMaxSize: () => ModifierImpl;
    readonly height: (value: number | string, unit?: string) => ModifierImpl;
    readonly width: (value: number | string, unit?: string) => ModifierImpl;
    readonly background: (color: ColorToken | string) => ModifierImpl;
    readonly weight: (weight: number, fill?: boolean) => ModifierImpl;
    readonly weightNoFill: (weight: number) => ModifierImpl;
    readonly marginTop: (value: number, unit?: string) => ModifierImpl;
    readonly clip: (shape: Shape) => ModifierImpl;
    readonly size: (value: number | string, unit?: string) => ModifierImpl;
};
export type Modifier = ModifierImpl;
export {};
